### PR TITLE
Add missing documentation and update to conform to PEP 8 standards

### PR DESCRIPTION
**Pull request by john-breton**
Functionally, everything should be equivalent. However, the following is of note:
- In errors.py, class BadPathError has been elevated from just a tagging class to a class responsible for the printing of the bad path error message. This was done so that in the future, should the error be raised all that needs to be passed is the path that caused the error and the message will be printed. This eliminates the need to have to rewrite the error message in other parts of the code. 
- The split_master.sh script has been changed since there was whitespace where there should not have been. I believe the script now functions correctly. However, my bash is rusty so if something seems off, it probably is.
- Two things in patch.py:
  - Theoretically, the program would crash if it did not detect any drives. This should never happen, but to be safe mnt is now defined globally to prevent this from happening. 
  - Default arguments that are mutable have been changed to avoid nasty bugs. More info [here](https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments).
- The mutable argument change was also made in api.py

Please let me know if something doesn't work or if this is not a useful pull request. My Python is rusty as I come from a Java/C background. Thanks for your consideration!

### CODE REVIEW

**Comment by meanmedianmoge** [comment]
Changes look good to me, approved. If you have any questions about Pythonic conventions used, just let me know.

Did you have an issue with cloning and committing to the repository? Just curious about the fork.

**Comment by john-breton** [comment]
I was able to clone the main repo, but I didn't have permission to commit to it, so I made a fork and commited there.

**Comment by meanmedianmoge** [comment]
Give it a try now to a feature branch, I just invited you to be an “official” collaborator.

**Comment by john-breton** [comment]
Thanks! I'm able to commit directly now :)

**Pull request merged**
