### PR TITLE
Patch deletion

### LINKED ISSUE #15: Create unit tests that cover the deletion of patches
- Create a unit test that confirms a patch is deleted successfully from the application directory.
  - Extend the test to ensure that other files remain unaffected by the deletion.
  - Extend the test to ensure that requesting the deletion of a file that does not exist does not produce unexpected deletions.
  - Extend the test to ensure that the accompanying metadata is also deleted when a patch has been marked for deletion.
  - Extend the test to ensure that if multiple versions of a patch exist, only the desired version is deleted.

- Create a unit test that confirms a patch is deleted successfully from an SD card.
  - Extend the test to ensure that other files remain unaffected by the deletion.
  - Extend the test to cover the case where a previously detected SD card is removed and the specified path cannot be accessed. 
   - Extend the test to ensure that requesting the deletion of a file that does not exist does not produce unexpected deletions.

### PR DESCRIPTION
**Pull request by john-breton**
This pull request address resolves #15 by implementing the backend patch deletion and validating the functionality through unit tests.

### CODE REVIEW

**Comment by john-breton** [comment]
Before merging, I would just like the peace of mind knowing that it actually works on macOS (and if it doesn't I will try to correct the issue)!

**Comment by john-breton** [comment]
As long as these new changes correctly function on OSX, we can go ahead and merge into testing_update. 
I also forgot to mention in the most recent commit, but I implemented the renaming of LibraryApp to ZoiaLibraryApp across the project as suggested by Matt.

**Comment by john-breton** [comment]
I did not know that setUp and tearDown were not implicitly called after each unit test. The more you know!

**Comment by meanmedianmoge** [comment]
You can also set it up sequentially in a Makefile! But that's a bit more overhead - just calling them within the other testing methods works perfectly fine.

**Pull request merged**
